version: '3.8'

services:
  nuvex:
    build: .
    container_name: nuvex-agent
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./dummy_data:/app/dummy_data
