# app/utils/log_writer.py

import os

def save_log_instructions(offense_id: str, instructions: str, base_dir: str = "logs/instructions") -> str:
    """
    Saves the given log investigation instructions into a .txt file.
    
    Args:
        offense_id (str): Unique offense ID or timestamp.
        instructions (str): Plaintext instructions generated by the model.
        base_dir (str): Directory to save the logs (default: logs/instructions).

    Returns:
        str: Path to the saved file or None if an error occurs.
    """
    try:
        os.makedirs(base_dir, exist_ok=True)
        filename = f"offense_{offense_id}.txt"
        filepath = os.path.join(base_dir, filename)

        with open(filepath, "w") as f:
            f.write(instructions)

        return filepath
    except OSError as e:
        print(f"Error writing log instructions for offense {offense_id}: {e}")
        return None
